import { NextRequest, NextResponse } from "next/server";
import { db as prisma } from "@/lib/db";
import { 
  getSalesReport, 
  getInventoryReport, 
  getLogisticsReport 
} from "@/app/merchant/reports/actions";
import { sendEmail } from "@/lib/mail";
import { startOfDay, endOfDay, subDays } from "date-fns";
import * as XLSX from "xlsx";

export async function GET(req: NextRequest) {
  // Optional: Security check
  // const authHeader = req.headers.get("authorization");
  // if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const subscriptions = await prisma.reportSubscription.findMany({
      where: { isActive: true },
      include: { merchantStore: true }
    });

    const results = [];

    for (const sub of subscriptions) {
      if (isDue(sub)) {
        try {
          await processReport(sub);
          results.push({ id: sub.id, status: "sent" });
        } catch (err: any) {
          console.error(`Failed to process subscription ${sub.id}:`, err);
          results.push({ id: sub.id, status: "failed", error: err.message });
        }
      } else {
        results.push({ id: sub.id, status: "skipped" });
      }
    }

    return NextResponse.json({ processed: results.length, details: results });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

function isDue(sub: any) {
  if (!sub.lastSentAt) return true;

  const now = new Date();
  const last = new Date(sub.lastSentAt);
  const diffMs = now.getTime() - last.getTime();
  const diffDays = diffMs / (1000 * 60 * 60 * 24);

  if (sub.frequency === "DAILY") return diffDays >= 1;
  if (sub.frequency === "WEEKLY") return diffDays >= 7;
  if (sub.frequency === "MONTHLY") return diffDays >= 30;

  return false;
}

async function processReport(sub: any) {
  const end = endOfDay(new Date());
  const start = sub.frequency === "DAILY" ? startOfDay(subDays(new Date(), 1)) 
              : sub.frequency === "WEEKLY" ? startOfDay(subDays(new Date(), 7))
              : startOfDay(subDays(new Date(), 30));

  let reportData;
  if (sub.reportType === "SALES") reportData = await getSalesReport(sub.merchantStoreId, start, end);
  else if (sub.reportType === "INVENTORY") reportData = await getInventoryReport(sub.merchantStoreId);
  else if (sub.reportType === "LOGISTICS") reportData = await getLogisticsReport(sub.merchantStoreId, start, end);
  else throw new Error("Unsupported report type");

  if (!reportData?.tableData || reportData.tableData.length === 0) {
    console.log(`No data for ${sub.reportType} report for store ${sub.merchantStoreId}. Skipping.`);
    return;
  }

  // Generate Excel
  const worksheet = XLSX.utils.json_to_sheet(reportData.tableData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sub.reportType);
  const buffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });

  const subject = `[Automated] ${sub.reportType} Report - ${sub.merchantStore.name}`;
  const html = `
    <div style="font-family: sans-serif; padding: 20px;">
      <h2>Your Automated Business Intelligence Report is Ready</h2>
      <p>Store: <b>${sub.merchantStore.name}</b></p>
      <p>Report Type: <b>${sub.reportType}</b></p>
      <p>Frequency: <b>${sub.frequency}</b></p>
      <hr />
      <p>Find the detailed Excel report attached to this email.</p>
      <p style="font-size: 12px; color: #666;">Generated by BusinessConnect Intelligence Engine.</p>
    </div>
  `;

  const sent = await sendEmail({
    to: sub.email,
    subject,
    html,
    attachments: [
      {
        filename: `${sub.reportType}_Report_${new Date().toISOString().split('T')[0]}.xlsx`,
        content: buffer
      }
    ]
  });

  if (sent) {
    await prisma.reportSubscription.update({
      where: { id: sub.id },
      data: { lastSentAt: new Date() }
    });
  }
}
