tunnel: 094d579e-06a6-4e78-8554-992bf307e82f
credentials-file: C:\Users\whmroot\.cloudflared\094d579e-06a6-4e78-8554-992bf307e82f.json

ingress:
  # Main Domain
  - hostname: businessconnect.bd
    service: http://localhost:3040
  
  # Wildcard for Storefronts (e.g. gadget-gear.businessconnect.bd)
  - hostname: "*.businessconnect.bd"
    service: http://localhost:3040

  # Default 404
  - service: http_status:404
